name: Django CI/CD

on:
  push:
    branches:
      - main 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11,3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Build static files
      run: |
        cd src/gseproject
        python manage.py collectstatic --noinput 

    - name: Run tests
      run: |
        python manage.py test 
      
